stages:
  - gh_create_release
  - dbuild

before_script:
  - DOCKERHUB='noxinmortus'
  - echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USER} --password-stdin

.build_template:
  when: manual
  interruptible: true
  tags:
    - docker

gh_create_release:
  extends: .build_template
  stage: gh_create_release
  script:
    - chmod +x gh-release.sh
    - bash gh-release.sh
  tags:
    - docker

build_arm/v7:
  extends: .build_template
  stage: dbuild
  script:
    - docker buildx build --build-arg GITHUB_USER=${GITHUB_USER} --build-arg GITHUB_REPOSITORY=${CI_PROJECT_NAME} --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} -t ${DOCKERHUB}/${CI_PROJECT_NAME}:latest --platform=linux/arm/v7 .

build_s390x:
  extends: .build_template
  stage: dbuild
  script:
    - docker buildx build --build-arg GITHUB_USER=${GITHUB_USER} --build-arg GITHUB_REPOSITORY=${CI_PROJECT_NAME} --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} -t ${DOCKERHUB}/${CI_PROJECT_NAME}:latest --platform=linux/s390x .
  tags:
    - docker-qemu-backports

build_ppc64le:
  extends: .build_template
  stage: dbuild
  script:
    - docker buildx build --build-arg GITHUB_USER=${GITHUB_USER} --build-arg GITHUB_REPOSITORY=${CI_PROJECT_NAME} --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} -t ${DOCKERHUB}/${CI_PROJECT_NAME}:latest --platform=linux/ppc64le .

build_arm64:
  extends: .build_template
  stage: dbuild
  script:
    - docker buildx build --build-arg GITHUB_USER=${GITHUB_USER} --build-arg GITHUB_REPOSITORY=${CI_PROJECT_NAME} --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} -t ${DOCKERHUB}/${CI_PROJECT_NAME}:latest --platform=linux/arm64 .

build_amd64:
  extends: .build_template
  stage: dbuild
  script:
    - docker buildx build --build-arg GITHUB_USER=${GITHUB_USER} --build-arg GITHUB_REPOSITORY=${CI_PROJECT_NAME} --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} -t ${DOCKERHUB}/${CI_PROJECT_NAME}:latest --platform=linux/amd64 .

build_386:
  extends: .build_template
  stage: dbuild
  script:
    - docker buildx build --build-arg GITHUB_USER=${GITHUB_USER} --build-arg GITHUB_REPOSITORY=${CI_PROJECT_NAME} --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} -t ${DOCKERHUB}/${CI_PROJECT_NAME}:latest --platform=linux/386 -f Dockerfile.openjdk .

build_mips64le:
  extends: .build_template
  stage: dbuild
  script:
    - docker buildx build --build-arg GITHUB_USER=${GITHUB_USER} --build-arg GITHUB_REPOSITORY=${CI_PROJECT_NAME} --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} -t ${DOCKERHUB}/${CI_PROJECT_NAME}:latest --platform=linux/mips64le -f Dockerfile.openjdk .
